// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace teamseven.PhyGen.Repository.Models;

public partial class Image
{
    public Image() { }

    public Image(string imageUrl, string details)
    {
        this.ImageUrl = imageUrl;
        this.Details = details;
    }

    public int ImageId { get; set; }

    public string ImageUrl { get; set; }

    public string? Details { get; set; }

    public DateTime? UploadedAt { get; set; }
}