// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace teamseven.PhyGen.Repository.Models;

public partial class Solution
{
    public int Id { get; set; }

    public int QuestionId { get; set; }

    [Required, MaxLength(5000)]
    public string Content { get; set; }

    [MaxLength(10000)]
    public string Explanation { get; set; } // from gemini flash

    [MaxLength(10000)]
    public string PythonScript { get; set; } // Script Python from DeepSeek R1

    [MaxLength(1000)]
    public string Mp4Url { get; set; } // URL MP4 from Genesis

    public bool IsMp4Generated { get; set; } // to scanned

    public bool IsMp4Reused { get; set; } // if reused

    public int? OriginalSolutionId { get; set; } // naviated to solution if reused

    public byte[] VideoData { get; set; } // NEW: Lưu nội dung video
    public string VideoContentType { get; set; } // NEW: Lưu kiểu file (video/mp4)


    public int CreatedByUserId { get; set; }

    public bool IsApproved { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Question Question { get; set; }

    public virtual Solution OriginalSolution { get; set; } 

    public virtual ICollection<SolutionReport> SolutionReports { get; set; } = new List<SolutionReport>();
}