// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace teamseven.PhyGen.Repository.Models;

public partial class SolutionReport
{
    public int Id { get; set; }

    public int SolutionId { get; set; }

    public int ReportedByUserId { get; set; }

    [Required, MaxLength(1000)]
    public string Reason { get; set; } 

    public DateTime ReportDate { get; set; }

    public virtual User ReportedByUser { get; set; }

    public virtual Solution Solution { get; set; }
}