// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace teamseven.PhyGen.Repository.Models;

public partial class SolutionsLink
{
    public int Id { get; set; }

    public int SolutionId { get; set; }

    public string Link { get; set; }

    public string GeneratedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Solution Solution { get; set; }
}