// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace teamseven.PhyGen.Repository.Models;

public partial class Solution
{
    public int Id { get; set; }

    public int QuestionId { get; set; }

    public string Content { get; set; }

    public long CreatedByUserId { get; set; }

    public bool IsApproved { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Question Question { get; set; }

    public virtual ICollection<SolutionReport> SolutionReports { get; set; } = new List<SolutionReport>();

    public virtual ICollection<SolutionsLink> SolutionsLinks { get; set; } = new List<SolutionsLink>();
}