// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace teamseven.PhyGen.Repository.Models;

public partial class SubscriptionType
{
    public int Id { get; set; }

    public string SubscriptionCode { get; set; }

    public string SubscriptionName { get; set; }

    public decimal SubscriptionPrice { get; set; }

    public int? DurationInDays { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public long? UpdatedBy { get; set; }

    public virtual User UpdatedByNavigation { get; set; }

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}