// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace teamseven.PhyGen.Repository.Models;

public partial class UserSubscription
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public int SubscriptionTypeId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool IsActive { get; set; }

    public string PaymentStatus { get; set; }

    public decimal? Amount { get; set; }

    public string PaymentGatewayTransactionId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual SubscriptionType SubscriptionType { get; set; }

    public virtual User User { get; set; }
}