// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace teamseven.PhyGen.Repository.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string EncryptedPassword { get; set; }

    public string Role { get; set; }

    public string LoginType { get; set; }

    public string FacebookId { get; set; }

    public string GoogleId { get; set; }

    public string FullName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsActive { get; set; }

    public int? ImageId { get; set; }
}