// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace teamseven.PhyGen.Repository.Models;

public partial class UserSocialProvider
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string ProviderName { get; set; }

    public string ProviderId { get; set; }

    public string Email { get; set; }

    public string ProfileUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}