// <auto-generated> This file has been auto generated for PostgreSQL with Supabase. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;

namespace teamseven.PhyGen.Repository.Models;

public partial class teamsevenphygendbContext : DbContext
{
    public teamsevenphygendbContext()
    {
    }

    public teamsevenphygendbContext(DbContextOptions<teamsevenphygendbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Chapter> Chapters { get; set; }
    public virtual DbSet<Exam> Exams { get; set; }
    public virtual DbSet<ExamHistory> ExamHistories { get; set; }
    public virtual DbSet<ExamQuestion> ExamQuestions { get; set; }
    public virtual DbSet<ExamType> ExamTypes { get; set; }
    public virtual DbSet<Grade> Grades { get; set; }
    public virtual DbSet<Lesson> Lessons { get; set; }
    public virtual DbSet<Question> Questions { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    public virtual DbSet<Semester> Semesters { get; set; }
    public virtual DbSet<Solution> Solutions { get; set; }
    public virtual DbSet<SolutionReport> SolutionReports { get; set; }
    public virtual DbSet<SolutionsLink> SolutionsLinks { get; set; }
    public virtual DbSet<SubscriptionType> SubscriptionTypes { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserSocialProvider> UserSocialProviders { get; set; }
    public virtual DbSet<UserSubscription> UserSubscriptions { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString ?? throw new InvalidOperationException("Connection string not found.");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseNpgsql(GetConnectionString("DefaultConnection"),
            options => options.EnableRetryOnFailure(maxRetryCount: 5, maxRetryDelay: TimeSpan.FromSeconds(10), null))
                         .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_chapters");
            entity.ToTable("chapters", "public");
            entity.HasIndex(e => e.SemesterId, "ix_chapters_semester_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(100);
            entity.HasOne(d => d.Semester).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.SemesterId)
                .HasConstraintName("fk_chapters_semester_id");
        });

        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_exams");
            entity.ToTable("exams", "public");
            entity.HasIndex(e => e.CreatedByUserId, "ix_exams_created_by_user_id");
            entity.HasIndex(e => e.ExamTypeId, "ix_exams_exam_type_id");
            entity.HasIndex(e => e.IsDeleted, "ix_exams_is_deleted");
            entity.HasIndex(e => e.LessonId, "ix_exams_lesson_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(100);
            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Exams)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_exams_created_by_user_id");
            entity.HasOne(d => d.ExamType).WithMany(p => p.Exams)
                .HasForeignKey(d => d.ExamTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_exams_exam_type_id");
            entity.HasOne(d => d.Lesson).WithMany(p => p.Exams)
                .HasForeignKey(d => d.LessonId)
                .HasConstraintName("fk_exams_lesson_id");
        });

        modelBuilder.Entity<ExamHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_exam_histories");
            entity.ToTable("exam_histories", "public");
            entity.HasIndex(e => e.ExamId, "ix_exam_histories_exam_id");
            entity.HasIndex(e => e.ActionByUserId, "ix_exam_histories_action_by_user_id");
            entity.Property(e => e.Action).IsRequired().HasMaxLength(50);
            entity.Property(e => e.ActionDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.HasOne(d => d.ActionByUser).WithMany(p => p.ExamHistories)
                .HasForeignKey(d => d.ActionByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_exam_histories_action_by_user_id");
            entity.HasOne(d => d.Exam).WithMany(p => p.ExamHistories)
                .HasForeignKey(d => d.ExamId)
                .HasConstraintName("fk_exam_histories_exam_id");
        });

        modelBuilder.Entity<ExamQuestion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_exam_questions");
            entity.ToTable("exam_questions", "public");
            entity.HasIndex(e => e.ExamId, "ix_exam_questions_exam_id");
            entity.HasIndex(e => e.QuestionId, "ix_exam_questions_question_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Order).IsRequired();
            entity.HasOne(d => d.Exam).WithMany(e => e.ExamQuestions)
                .HasForeignKey(d => d.ExamId)
                .HasConstraintName("fk_exam_questions_exam_id");
            entity.HasOne(d => d.Question).WithMany()
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_exam_questions_question_id");
        });

        modelBuilder.Entity<ExamType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_exam_types");
            entity.ToTable("exam_types", "public");
            entity.HasIndex(e => e.Name, "uq_exam_types_name").IsUnique();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(50);
        });

        modelBuilder.Entity<Grade>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_grades");
            entity.ToTable("grades", "public");
            entity.HasIndex(e => e.Name, "uq_grades_name").IsUnique();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(50);
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_lessons");
            entity.ToTable("lessons", "public");
            entity.HasIndex(e => e.ChapterId, "ix_lessons_chapter_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(100);
            entity.HasOne(d => d.Chapter).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.ChapterId)
                .HasConstraintName("fk_lessons_chapter_id");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_questions");
            entity.ToTable("questions", "public");
            entity.HasIndex(e => e.CreatedByUserId, "ix_questions_created_by_user_id");
            entity.HasIndex(e => e.LessonId, "ix_questions_lesson_id");
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.DifficultyLevel).HasMaxLength(20);
            entity.Property(e => e.QuestionSource).IsRequired().HasMaxLength(50);
            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Questions)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_questions_created_by_user_id");
            entity.HasOne(d => d.Lesson).WithMany(p => p.Questions)
                .HasForeignKey(d => d.LessonId)
                .HasConstraintName("fk_questions_lesson_id");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_roles");
            entity.ToTable("roles", "public");
            entity.HasIndex(e => e.RoleName, "uq_roles_role_name").IsUnique();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RoleName).IsRequired().HasMaxLength(255);
        });

        modelBuilder.Entity<Semester>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_semesters");
            entity.ToTable("semesters", "public");
            entity.HasIndex(e => e.GradeId, "ix_semesters_grade_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(10);
            entity.HasOne(d => d.Grade).WithMany(p => p.Semesters)
                .HasForeignKey(d => d.GradeId)
                .HasConstraintName("fk_semesters_grade_id");
        });

        modelBuilder.Entity<Solution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_solutions");
            entity.ToTable("solutions", "public");
            entity.HasIndex(e => e.CreatedByUserId, "ix_solutions_created_by_user_id");
            entity.HasIndex(e => e.IsApproved, "ix_solutions_is_approved");
            entity.HasIndex(e => e.IsDeleted, "ix_solutions_is_deleted");
            entity.HasIndex(e => e.QuestionId, "ix_solutions_question_id");
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.Explanation);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.IsApproved).HasDefaultValue(true);
            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Solutions)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_solutions_created_by_user_id");
            entity.HasOne(d => d.Question).WithMany(p => p.Solutions)
                .HasForeignKey(d => d.QuestionId)
                .HasConstraintName("fk_solutions_question_id");
        });

        modelBuilder.Entity<SolutionReport>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_solution_reports");
            entity.ToTable("solution_reports", "public");
            entity.HasIndex(e => e.ReportedByUserId, "ix_solution_reports_reported_by_user_id");
            entity.HasIndex(e => e.SolutionId, "ix_solution_reports_solution_id");
            entity.Property(e => e.Reason).IsRequired().HasMaxLength(500);
            entity.Property(e => e.ReportDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Status).IsRequired().HasMaxLength(20).HasDefaultValue("Pending");
            entity.HasOne(d => d.ReportedByUser).WithMany(p => p.SolutionReports)
                .HasForeignKey(d => d.ReportedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_solution_reports_reported_by_user_id");
            entity.HasOne(d => d.Solution).WithMany(p => p.SolutionReports)
                .HasForeignKey(d => d.SolutionId)
                .HasConstraintName("fk_solution_reports_solution_id");
        });

        modelBuilder.Entity<SolutionsLink>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_solutions_links");
            entity.ToTable("solutions_links", "public");
            entity.HasIndex(e => e.SolutionId, "ix_solutions_links_solution_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.GeneratedBy).HasMaxLength(50);
            entity.Property(e => e.Link).HasMaxLength(500);
            entity.HasOne(d => d.Solution).WithMany(p => p.SolutionsLinks)
                .HasForeignKey(d => d.SolutionId)
                .HasConstraintName("fk_solutions_links_solution_id");
        });

        modelBuilder.Entity<SubscriptionType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_subscription_types");
            entity.ToTable("subscription_types", "public");
            entity.HasIndex(e => e.SubscriptionCode, "ix_subscription_types_subscription_code");
            entity.HasIndex(e => e.UpdatedBy, "ix_subscription_types_updated_by");
            entity.HasIndex(e => e.SubscriptionCode, "uq_subscription_types_subscription_code").IsUnique();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.SubscriptionCode).IsRequired().HasMaxLength(50);
            entity.Property(e => e.SubscriptionName).IsRequired().HasMaxLength(255);
            entity.Property(e => e.SubscriptionPrice).HasColumnType("numeric(18,2)");
            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.SubscriptionTypes)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_subscription_types_updated_by");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_users");
            entity.ToTable("users", "public");
            entity.HasIndex(e => e.Email, "ix_users_email");
            entity.HasIndex(e => e.IsActive, "ix_users_is_active");
            entity.HasIndex(e => e.LastLoginAt, "ix_users_last_login_at");
            entity.HasIndex(e => e.RoleId, "ix_users_role_id");
            entity.HasIndex(e => e.UpdatedBy, "ix_users_updated_by");
            entity.HasIndex(e => e.Email, "uq_users_email").IsUnique();
            entity.Property(e => e.AvatarUrl).HasMaxLength(1024);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Email).IsRequired().HasMaxLength(255);
            entity.Property(e => e.FullName).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordHash).HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_users_role_id");
            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.InverseUpdatedByNavigation)
                .HasForeignKey(d => d.UpdatedBy)
                .HasConstraintName("fk_users_updated_by");
        });

        modelBuilder.Entity<UserSocialProvider>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_user_social_providers");
            entity.ToTable("user_social_providers", "public");
            entity.HasIndex(e => e.UserId, "ix_user_social_providers_user_id");
            entity.HasIndex(e => new { e.ProviderName, e.ProviderId }, "uq_user_social_providers_provider").IsUnique();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.ProfileUrl).HasMaxLength(2048);
            entity.Property(e => e.ProviderId).IsRequired().HasMaxLength(255);
            entity.Property(e => e.ProviderName).IsRequired().HasMaxLength(50);
            entity.HasOne(d => d.User).WithMany(p => p.UserSocialProviders)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_user_social_providers_user_id");
        });

        modelBuilder.Entity<UserSubscription>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_user_subscriptions");
            entity.ToTable("user_subscriptions", "public");
            entity.HasIndex(e => e.IsActive, "ix_user_subscriptions_is_active");
            entity.HasIndex(e => e.PaymentStatus, "ix_user_subscriptions_payment_status");
            entity.HasIndex(e => e.SubscriptionTypeId, "ix_user_subscriptions_subscription_type_id");
            entity.HasIndex(e => e.UserId, "ix_user_subscriptions_user_id");
            entity.Property(e => e.Amount).HasColumnType("numeric(18,2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PaymentGatewayTransactionId).HasMaxLength(255);
            entity.Property(e => e.PaymentStatus).IsRequired().HasMaxLength(50);
            entity.Property(e => e.StartDate).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.HasOne(d => d.SubscriptionType).WithMany(p => p.UserSubscriptions)
                .HasForeignKey(d => d.SubscriptionTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user_subscriptions_subscription_type_id");
            entity.HasOne(d => d.User).WithMany(p => p.UserSubscriptions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_user_subscriptions_user_id");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}